import 'package:flutter/material.dart';

final List<Map<String, dynamic>> actividades = [
  {
    "fecha": DateTime(2023, 10, 24),
    "tipo": "Edición",
    "tagColor": const Color(0xFFF2994A),
    "icono": Icons.edit_outlined,
    "iconoColor": const Color(0xFF2E6BF2),
    "iconoBg": const Color(0xFFEAF2FE),
    "hora": "14:32",
    "usuarioCorto": "maria.g",
    "tituloNormal": "María Gómez editó el producto: ",
    "tituloBold": "Pastel de Trufa",
    "descripcion":
        "Se actualizó el precio de \$45.00 a \$48.00 y se modificó la descripción.",
    "detalle": {
      "fechaHora": "24 Octubre 2023 - 02:32 PM",
      "usuarioNombre": "María Gómez",
      "usuarioEmail": "maria.g • Cajero / Tienda",
      "productoNombre": "Pastel de Trufa",
      "productoSku": "PST-TRF-081",
      "productoCategoria": "Repostería",
      "descripcionLarga":
          "Se actualizó el precio de \$45.00 a \$48.00 y se modificó la descripción del producto para el catálogo del día.",
      "valorAnterior": "\$45.00",
      "valorNuevo": "\$48.00",
      "estadoOperacion": "Modificación guardada",
    },
  },
  {
    "fecha": DateTime(2023, 10, 24),
    "tipo": "Eliminación",
    "tagColor": const Color(0xFFEB5757),
    "icono": Icons.delete_outline,
    "iconoColor": const Color(0xFFEB5757),
    "iconoBg": const Color(0xFFFDEDED),
    "hora": "11:15",
    "usuarioCorto": "carlos.s",
    "tituloNormal": "Admin eliminó el usuario: ",
    "tituloBold": "Juan Pérez",
    "descripcion": "Usuario inactivo eliminado del sistema.",
    "detalle": {
      "fechaHora": "24 Octubre 2023 - 11:15 AM",
      "usuarioNombre": "Carlos Soto",
      "usuarioEmail": "carlos.s • Administrador",
      "productoNombre": "Juan Pérez",
      "productoSku": "Usuario del sistema",
      "productoCategoria": "Cuenta",
      "descripcionLarga":
          "Usuario inactivo eliminado del sistema por falta de uso durante más de 6 meses.",
      "valorAnterior": null,
      "valorNuevo": null,
      "estadoOperacion": "Eliminación completada",
    },
  },
  {
    "fecha": DateTime(2026, 9, 26),
    "tipo": "Acceso",
    "tagColor": const Color(0xFF16233F),
    "icono": Icons.login,
    "iconoColor": Colors.white,
    "iconoBg": const Color(0xFF16233F),
    "hora": "08:05",
    "usuarioCorto": "admin.principal",
    "tituloNormal": "Nuevo inicio de sesión ",
    "tituloBold": "exitoso",
    "descripcion":
        "Inicio de sesión desde IP: 192.168.1.45 (Dispositivo móvil).",
    "detalle": {
      "fechaHora": "24 Octubre 2023 - 08:05 AM",
      "usuarioNombre": "Admin Principal",
      "usuarioEmail": "admin.principal • Administrador",
      "productoNombre": "Inicio de sesión",
      "productoSku": "IP: 192.168.1.45",
      "productoCategoria": "Dispositivo móvil",
      "descripcionLarga":
          "Inicio de sesión exitoso desde un dispositivo móvil registrado previamente.",
      "valorAnterior": null,
      "valorNuevo": null,
      "estadoOperacion": "Acceso concedido",
    },
  },

  // 4
  {
    "fecha": DateTime(2026, 9, 26),
    "tipo": "Creación",
    "tagColor": const Color(0xFF27AE60),
    "icono": Icons.add_circle_outline,
    "iconoColor": const Color(0xFF27AE60),
    "iconoBg": const Color(0xFFE8F8EF),
    "hora": "16:20",
    "usuarioCorto": "maria.g",
    "tituloNormal": "María Gómez creó el producto: ",
    "tituloBold": "Pastel de Chocolate",
    "descripcion": "Nuevo producto agregado al catálogo.",
    "detalle": {
      "fechaHora": "26 septiembre 2026 - 04:20 PM",
      "usuarioNombre": "María Gómez",
      "usuarioEmail": "maria.g • Cajero / Tienda",
      "productoNombre": "Pastel de Chocolate",
      "productoSku": "PST-CHO-102",
      "productoCategoria": "Repostería",
      "descripcionLarga":
          "Se registró un nuevo producto de repostería en el catálogo de la pastelería.",
      "valorAnterior": null,
      "valorNuevo": "\$50.00",
      "estadoOperacion": "Producto creado",
    },
  },

  // 5
  {
    "fecha": DateTime(2026, 10, 23),
    "tipo": "Edición",
    "tagColor": const Color(0xFFF2994A),
    "icono": Icons.edit_outlined,
    "iconoColor": const Color(0xFF2E6BF2),
    "iconoBg": const Color(0xFFEAF2FE),
    "hora": "13:45",
    "usuarioCorto": "carlos.s",
    "tituloNormal": "Carlos Soto actualizó el stock de: ",
    "tituloBold": "Pastel de Fresa",
    "descripcion": "Se modificó la cantidad disponible del producto.",
    "detalle": {
      "fechaHora": "23 Octubre 2026 - 01:45 PM",
      "usuarioNombre": "Carlos Soto",
      "usuarioEmail": "carlos.s • Administrador",
      "productoNombre": "Pastel de Fresa",
      "productoSku": "PST-FRE-054",
      "productoCategoria": "Repostería",
      "descripcionLarga":
          "Se actualizó la cantidad disponible del producto debido a una entrada de inventario.",
      "valorAnterior": "12 unidades",
      "valorNuevo": "25 unidades",
      "estadoOperacion": "Inventario actualizado",
    },
  },

  // 6
  {
    "fecha": DateTime(2026, 10, 23),
    "tipo": "Venta",
    "tagColor": const Color(0xFF2E6BF2),
    "icono": Icons.shopping_cart_outlined,
    "iconoColor": const Color(0xFF2E6BF2),
    "iconoBg": const Color(0xFFEAF2FE),
    "hora": "12:10",
    "usuarioCorto": "maria.g",
    "tituloNormal": "María Gómez registró una venta: ",
    "tituloBold": "Venta #00125",
    "descripcion": "Venta registrada correctamente en el sistema.",
    "detalle": {
      "fechaHora": "26 Octubre 2026 - 12:10 PM",
      "usuarioNombre": "María Gómez",
      "usuarioEmail": "maria.g • Cajero / Tienda",
      "productoNombre": "Venta #00125",
      "productoSku": "VNT-00125",
      "productoCategoria": "Venta",
      "descripcionLarga":
          "Se registró una nueva venta con productos de repostería y se actualizó el inventario correspondiente.",
      "valorAnterior": null,
      "valorNuevo": "\$85.00",
      "estadoOperacion": "Venta registrada",
    },
  },

  // 7
  {
    "fecha": DateTime(2023, 10, 22),
    "tipo": "Acceso",
    "tagColor": const Color(0xFF16233F),
    "icono": Icons.login,
    "iconoColor": Colors.white,
    "iconoBg": const Color(0xFF16233F),
    "hora": "09:30",
    "usuarioCorto": "carlos.s",
    "tituloNormal": "Carlos Soto inició sesión ",
    "tituloBold": "correctamente",
    "descripcion":
        "Inicio de sesión desde IP: 192.168.1.20 (Computadora).",
    "detalle": {
      "fechaHora": "22 Octubre 2023 - 09:30 AM",
      "usuarioNombre": "Carlos Soto",
      "usuarioEmail": "carlos.s • Administrador",
      "productoNombre": "Inicio de sesión",
      "productoSku": "IP: 192.168.1.20",
      "productoCategoria": "Computadora",
      "descripcionLarga":
          "Inicio de sesión exitoso desde una computadora registrada en el sistema.",
      "valorAnterior": null,
      "valorNuevo": null,
      "estadoOperacion": "Acceso concedido",
    },
  },

  // 8
  {
    "fecha": DateTime(2023, 10, 22),
    "tipo": "Edición",
    "tagColor": const Color(0xFFF2994A),
    "icono": Icons.edit_outlined,
    "iconoColor": const Color(0xFF2E6BF2),
    "iconoBg": const Color(0xFFEAF2FE),
    "hora": "10:45",
    "usuarioCorto": "admin.principal",
    "tituloNormal": "Admin actualizó el producto: ",
    "tituloBold": "Cupcakes de Vainilla",
    "descripcion": "Se modificó el precio del producto.",
    "detalle": {
      "fechaHora": "22 Octubre 2023 - 10:45 AM",
      "usuarioNombre": "Admin Principal",
      "usuarioEmail": "admin.principal • Administrador",
      "productoNombre": "Cupcakes de Vainilla",
      "productoSku": "CUP-VAI-033",
      "productoCategoria": "Repostería",
      "descripcionLarga":
          "Se actualizó el precio del producto para mantener actualizado el catálogo de ventas.",
      "valorAnterior": "\$30.00",
      "valorNuevo": "\$32.00",
      "estadoOperacion": "Modificación guardada",
    },
  },

  // 9
  {
    "fecha": DateTime(2023, 10, 21),
    "tipo": "Creación",
    "tagColor": const Color(0xFF27AE60),
    "icono": Icons.add_circle_outline,
    "iconoColor": const Color(0xFF27AE60),
    "iconoBg": const Color(0xFFE8F8EF),
    "hora": "15:25",
    "usuarioCorto": "carlos.s",
    "tituloNormal": "Carlos Soto registró el proveedor: ",
    "tituloBold": "Distribuidora San José",
    "descripcion": "Nuevo proveedor agregado al sistema.",
    "detalle": {
      "fechaHora": "21 Octubre 2023 - 03:25 PM",
      "usuarioNombre": "Carlos Soto",
      "usuarioEmail": "carlos.s • Administrador",
      "productoNombre": "Distribuidora San José",
      "productoSku": "PROV-045",
      "productoCategoria": "Proveedor",
      "descripcionLarga":
          "Se registró un nuevo proveedor para gestionar las compras y abastecimiento de productos.",
      "valorAnterior": null,
      "valorNuevo": "Proveedor activo",
      "estadoOperacion": "Proveedor registrado",
    },
  },


];